### ISSUE TITLE
Create proper relationships between Lines and Turns

### ISSUE THREAD

**Issue by fig** [fig/roster#2]
Use the `has_many through:` method
Will probably look like this:
```ruby
#app/models/line.rb
class Line < ActiveRecord::Base
  belongs_to :base_roster
  has_many :days
  has_many :turns, through: :days
```
```ruby
#app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :line
  belongs_to :turn
```
```ruby
#app/models/turn.rb
class Turn < ActiveRecord::Base
  has_many :days
  has_many :lines, through: :days
```
#### References
[How a has_many :through association works in practice](https://ducktypelabs.com/how-a-has_many-through-association-works-in-practice/)
[Rails Guides](http://guides.rubyonrails.org/v4.2/association_basics.html#the-has-many-through-association)
#### Tasks
- [x] Read and Learn
- [x] Impliment in Models
- [x] Clean-up Controllers
- [x] Clean-up Views
- [x] Do dependency injection properly
- [x] Think about [caching](http://guides.rubyonrails.org/v4.2/association_basics.html#controlling-caching)
